package Leetcode;
/*
    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Find the letter that was added in t.

    Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.
 */
public class Easy_FindDifference_389 {
    public char findTheDifference(String s, String t) {
        int[] smap = new int[26];
        int[] tmap = new int[26];
        for(int i = 0; i < s.length(); i++){
            smap[s.charAt(i) - 'a']++;
        }
        for(int i = 0; i < t.length(); i++){
            tmap[t.charAt(i) - 'a']++;
        }
        for(int i = 0; i < smap.length; i++){
            if(smap[i] != tmap[i]){
                return (char) (i + 'a');
            }
        }
        return '\0';
    }
}
